name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -f Dockerfile -t crafty-discord-bot:latest .

      - name: Save Docker image as TAR
        run: |
          docker save -o crafty-controller-bot.tar crafty-discord-bot:latest
          ls -lh my-image.tar

      - name: Upload Docker image TAR
        uses: actions/upload-artifact@v4
        with:
          name: crafty-controller-bot
          path: crafty-controller-bot.tar
          if-no-files-found: error
