name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag crafty-discord-bot:latest

      - name: Save Docker image
        run: docker save my-image:latest -o my-image.tar

      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: my-docker-image
          path: my-image.tar
          retention-days: 7
